#!/usr/bin/env node

/**
 * Quick Setup Script for Pakistani WhatsApp Bot
 * Run: node setup.js
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const question = (prompt) => new Promise(resolve => rl.question(prompt, resolve));

async function setup() {
    console.log('\n');
    console.log('╔════════════════════════════════════════════════════════╗');
    console.log('║     🇵🇰 Pakistani WhatsApp Bot - Setup Wizard          ║');
    console.log('║         Free MVP for Small Merchants                   ║');
    console.log('╚════════════════════════════════════════════════════════╝');
    console.log('\n');

    // Check if .env exists
    const envPath = path.join(__dirname, '.env');
    const envExamplePath = path.join(__dirname, '.env.example');

    if (fs.existsSync(envPath)) {
        const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/N): ');
        if (overwrite.toLowerCase() !== 'y') {
            console.log('\n✅ Setup cancelled. Existing .env preserved.\n');
            rl.close();
            return;
        }
    }

    console.log('📝 Let\'s configure your bot...\n');

    // Collect configuration
    const config = {};

    // Supabase
    console.log('📊 Supabase Configuration (https://supabase.com):');
    config.SUPABASE_URL = await question('  Supabase URL: ');
    config.SUPABASE_ANON_KEY = await question('  Supabase Anon Key: ');

    console.log('\n🤖 AI Provider Configuration:');
    console.log('  1. OpenRouter (50 requests/day free)');
    console.log('  2. Google Gemini (60 requests/min free)');
    const aiChoice = await question('  Choose (1 or 2): ');

    if (aiChoice === '2') {
        config.AI_PROVIDER = 'gemini';
        config.GEMINI_API_KEY = await question('  Gemini API Key: ');
        config.OPENROUTER_API_KEY = '';
        config.OPENROUTER_MODEL = '';
    } else {
        config.AI_PROVIDER = 'openrouter';
        config.OPENROUTER_API_KEY = await question('  OpenRouter API Key: ');
        config.OPENROUTER_MODEL = 'meta-llama/llama-3.3-70b-instruct';
        config.GEMINI_API_KEY = '';
    }

    console.log('\n⚙️  Bot Configuration:');
    config.MAX_AI_CALLS_PER_DAY = await question('  Max AI calls per day (default 50): ') || '50';
    config.PORT = await question('  Port (default 3000): ') || '3000';
    config.LOG_LEVEL = 'info';

    console.log('\n📱 Payment Numbers (for testing):');
    config.DEFAULT_EASYPAYSA_NUMBER = await question('  Easypaisa Number (03XXXXXXXXX): ');
    config.DEFAULT_JAZZCASH_NUMBER = await question('  JazzCash Number (03XXXXXXXXX): ');

    // Generate .env file
    let envContent = '# Pakistani WhatsApp Bot - Environment Variables\n';
    envContent += '# Generated by setup.js on ' + new Date().toISOString() + '\n\n';

    for (const [key, value] of Object.entries(config)) {
        envContent += `${key}=${value}\n`;
    }

    fs.writeFileSync(envPath, envContent);

    console.log('\n✅ .env file created successfully!\n');

    // Next steps
    console.log('📋 Next Steps:');
    console.log('  1. Run: npm install');
    console.log('  2. Setup Supabase tables (see README.md)');
    console.log('  3. Run: npm start');
    console.log('  4. Scan QR code with WhatsApp');
    console.log('  5. Send START to your bot number\n');

    console.log('📚 Documentation:');
    console.log('  • README.md - Full setup guide');
    console.log('  • TESTING.md - Testing scenarios');
    console.log('  • supabase-schema.sql - Database setup\n');

    rl.close();
}

setup().catch(err => {
    console.error('❌ Setup error:', err);
    rl.close();
    process.exit(1);
});
